# Generated by Django 5.2.2 on 2025-06-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado_cita', models.AutoField(primary_key=True, serialize=False)),
                ('estado_cita', models.CharField(choices=[('En progreso', 'En progreso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Bloqueado', 'Bloqueado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_observacion', models.CharField(choices=[('Puntualidad', 'Puntualidad'), ('Trato', 'Trato'), ('Servicio', 'Servicio'), ('Barbero', 'Barbero')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubServicio',
            fields=[
                ('id_subservicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='subservicios/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Barbero', 'Barbero'), ('Cliente', 'Cliente'), ('Barbería', 'Barbería')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('id_estado_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.estadocita')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_registro_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_original', models.FloatField()),
                ('total_pagado', models.FloatField()),
                ('fecha_pago', models.DateTimeField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.cita')),
                ('id_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion3.descuento')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.formapago')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_subservicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.subservicio'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contraseña_hash', models.CharField(max_length=255)),
                ('descripcion_usuario', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('id_estado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.estadousuario')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.tipousuario')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.usuario'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.usuario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to='gestion3.usuario'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_accion', models.TextField()),
                ('fecha_bitacora', models.DateTimeField()),
                ('tipo_accion', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionObservacion',
            fields=[
                ('id_valoracion_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.cita')),
                ('id_observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion3.observacion')),
            ],
        ),
    ]
