# Generated by Django 4.2.20 on 2025-06-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservicio',
            old_name='imagenes',
            new_name='imagen',
        ),
    ]
